apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-subgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-subgraph
  template:
    metadata:
      labels:
        app: user-subgraph
    spec:
      containers:
        - name: user-subgraph
          image: gcr.io/cosmo-exercise/my-subgraph:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
