coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false
server:
  enabled: true
  hostNetwork: false
  hostPID: false
  affinity: {}
alertmanager:
  enabled: true
  hostNetwork: false
  hostPID: false
  affinity: {}
pushgateway:
  enabled: true
  hostNetwork: false
  hostPID: false
  affinity: {}
kubeStateMetrics:
  enabled: true
  hostNetwork: false
  hostPID: false
  affinity: {}
