apiVersion: v1
data:
  graphApiToken: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKcGMzTWlPaUppWW1KbVlqTXpNQzAwTVdRNExUUm1ZelF0T1RRNFpTMHpZMkk1WTJWbVl6Z3haREVpTENKbVpXUmxjbUYwWldSZlozSmhjR2hmYVdRaU9pSTNOVFF5T0Roak1TMW1ZV1ExTFRSbU5EY3RPRGd5WkMwM1ptWmxZV1JsWmpFMVlqRWlMQ0poZFdRaU9pSmpiM050YnpwbmNtRndhQzFyWlhraUxDSnZjbWRoYm1sNllYUnBiMjVmYVdRaU9pSTRObU0zTURVNE5pMDFNVFkzTFRRMVpEa3RZamt5TXkwMk9ETTBZalkyTkdKbE5qQWlMQ0pwWVhRaU9qRTNORFF6TWpBeU56ZDkuQ1k5eHZoRHlWZFAtNU9kMW9CN3dTZ3ZzVFR4RzBUY3h6bnVQemMwNUY4Yw==
kind: Secret
metadata:
  creationTimestamp: "2025-04-11T13:48:49Z"
  name: router-secret
  namespace: default
  uid: 05b9b9fe-70d6-4730-83ef-cae46fc8c08b
type: Opaque
