apiVersion: v1
kind: Service
metadata:
  name: minimal-subgraph-service
spec:
  selector:
    app: user-subgraph
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
